# Generated by Django 5.1.5 on 2025-10-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('problem_type', models.CharField(max_length=20)),
                ('problem_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(choices=[('knapsack', 'Knapsack Problem'), ('tsp', 'Traveling Salesman Problem'), ('matching', 'Graph Matching Problem')], max_length=20)),
                ('algorithm', models.CharField(max_length=50)),
                ('problem_data', models.JSONField()),
                ('solution', models.JSONField()),
                ('objective_value', models.FloatField()),
                ('runtime_seconds', models.FloatField()),
                ('memory_mb', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
